
name: my-ticket app

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: lucky050/ticket-reservation

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build WAR
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:latest \
            -t ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          echo "✅ Pushed latest and ${{ github.sha }}"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: |
            set -e

            echo "===== Go to project directory ====="
            cd ~/ticket-reservation

            echo "===== Pull latest code ====="
            git pull origin main

            echo "===== Pull latest images ====="
            docker compose pull

            echo "===== Restart full stack ====="
            docker compose up -d

            echo "===== Wait for services ====="
            sleep 45

            echo "===== Show containers ====="
            docker compose ps

            echo "===== Check app health ====="
            curl -f http://localhost:8000/TRSApp/actuator/health

            echo "===== Check Nginx route with retries ====="
            for i in {1..10}; do
              if curl -f http://localhost/TRSApp/; then
                echo "✅ Nginx route is working"
                break
              fi

              echo "Nginx not ready yet, retrying in 10 seconds..."
              sleep 10

              if [ "$i" -eq 10 ]; then
                echo "❌ Nginx route failed after retries"
                exit 1
              fi
            done

            echo "===== Check Prometheus ====="
            curl -f http://localhost:9090/-/healthy

            echo "✅ Deployment completed successfully"
